debug: true


spring:
    profiles: development
    main.show-banner: true
    datasource:
        url: jdbc:postgresql://${DATABASE_IP}:5432/test_db
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        initialize: true

---

spring:
    profiles: production
    main.show-banner: true
    datasource:
        url: jdbc:postgresql://db:5432/test_db
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        initialize: true
