database:
  image: postgres:9.5
  container_name: postgres
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
   - POSTGRES_DB=test_db
  volumes:
   - ./src/test/resources/db:/docker-entrypoint-initdb.d
